[theme]
base = "dark"
primaryColor = "#0ea5e9"
backgroundColor = "#0b0e14"
secondaryBackgroundColor = "#161b24"
textColor = "#e5e7eb"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
